create table import_data_operations(
    id uuid primary key,
    import_data_entry_id uuid not null,
    import_type varchar(255) not null,
    date date not null,
    type varchar(255) not null,
    amount_from_value numeric not null,
    amount_from_currency varchar(255) not null,
    account_from_id uuid,
    amount_to_value numeric not null,
    amount_to_currency varchar(255) not null,
    account_to_id uuid,
    description varchar(255),
    raw jsonb not null,
    hint_input varchar(255),
    hint_id uuid,
    full_id uuid,
    selected boolean not null default false,
    distance double precision,
    foreign key (import_data_entry_id) references import_data_entries(id),
    foreign key (account_from_id) references accounts(id),
    foreign key (account_to_id) references accounts(id),
    foreign key (hint_id) references embeddings(id),
    foreign key (full_id) references embeddings(id)
);